name: xwidgets
channels:
- conda-forge
dependencies:
  # Build dependencies
- cmake
- cxx-compiler
- ninja
  # Host dependencies
- xeus=3.0.3
- cppzmq
- xproperty=0.11.0
- nlohmann_json=3.9.1
  # Test dependencies
- doctest >= 2.4.6
- json_schema_validator
- pre-commit
- cmake-format
# Not available on Win and downgrade Clang compiler on MacOS
- sel(linux): xeus-cling
- sel(linux): papermill
