name: xwidgets
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  # Host dependencies
  - xeus-zmq=1.0.0
  - cppzmq
  - xproperty=0.11.0
  - nlohmann_json=3.9.1
  # Test dependencies
  - doctest >= 2.4.6
